SELECT a.USER_ID, a.NICKNAME, CONCAT(a.CITY," ",a.STREET_ADDRESS1," ",a.STREET_ADDRESS2) AS 전체주소,
        CONCAT(SUBSTR(a.TLNO,1,3),'-',SUBSTR(a.TLNO,4,4),'-',SUBSTR(a.TLNO,8,4)) AS 전화번호
    FROM USED_GOODS_USER AS a
    join (SELECT WRITER_ID,count(*) FROM USED_GOODS_BOARD GROUP BY WRITER_ID having count(*)>=3) as c on a.USER_ID=c.WRITER_ID
    ORDER BY a.USER_ID DESC;